#pragma once

enum CONTROL_TYPE
{
	PLAYER_CONTROL = 0,
	FRONTEND_CONTROL = 2
};

enum CONTROL {
	INPUT_SKIP_CUTSCENE = 18,
	INPUT_CHARACTER_WHEEL = 19,
	INPUT_SPRINT = 21,
	INPUT_JUMP = 22,
	INPUT_ENTER = 22,
	INPUT_ATTACK = 24,
	INPUT_PHONE = 27,
	INPUT_SPECIAL_ABILITY = 28,
	INPUT_SELECT_WEAPON = 37,
	INPUT_COVER = 44,
	INPUT_RELOAD = 45,
	INPUT_DETONATE = 47,
	INPUT_MELEE_ATTACK_LIGHT = 140,
	INPUT_MELEE_ATTACK_HEAVY = 141,
	INPUT_MELEE_ATTACK_ALTERNATE = 142
};