#pragma once
/*
prologue1 = Prologue
armenian1 = Franklin & Lamar
armenian2 = Repossesion
franklin0 = Chop
armenian3 = Complications
family1 = Father & Son
family3 = Marriage Counseling
lester1 = Friend Request
family2 = Daddy's Little Girl
jewelry_setup1 = Casing the Jewel Store
jewelry_prep1b = Carbine Rifles
jewelry_heist = The Jewel Store Job
lamar1 = The Long Stretch
trevor1 = Mr.Philips
chinese1 = Trevor Philips Industries
trevor2 = Nervous Ron
chinese2 = Crystal Maze
trevor3 = Friends Reunited
family4 = Fame or Shame
fbi1 = Dead Man Walking
fbi2 = Three's Company
franklin1 = Hood Safari
docks_setup = Scouting the Port
family5 = Did Somebody Say Yoga ?
fbi3 = By The Book
docks_prep1 = Minisub
fbi4_intro = Blitz Play Intro
fbi4_prep1 = Garbage Truck
fbi4_prep5 = Boiler Suits
fbi4_prep2 = Tow Truck
fbi4_prep4 = Masks
docks_heista / docks_heistb = Merryweather Heist
assassin_valet = Hotel Assasination
fbi4 = Blitz Play Heist
carsteal1 = I Fought The Law
carsteal2 = Eye in the Sky
solomon1 = Mr.Richards
martin1 = Caida Libre
carsteal3 = Deep Inside
exile1 = Minor Turbulance
rural_bank_setup = Paleto Score Setup
exile2 = Predator
rural_bank_prep1 = Military Hardware
rural_bank_heist = Paleto Score
exile3 = Derailed
fbi5 = Monkey Business
trevor5 = Hang Ten
final_heist1 = Surveying the Score
michael1 = Bury the Hatchet
carsteal4 = Pack Man
michael2 = Fresh Meat
solomon2 = Ballad of Rocco
agency_heist1 = Cleaning Out The Bureau
family6 = Reuniting the Family
agency_heist2 = Architect's Plans
agency_heist3a / agency_heist3b = Bureau Raid
solomon3 = Legal Trouble
michael3 = The Wrap Up
franklin2 = Lamar Down
michael4 = Meltdown
finale_heist2_intro = Big Score Setup Intro
finale_heist_prepc = Gauntlet
finale_heist_prepa = Stingers
finale_heist2a / finale_heist2b = The Big One
finale_intro = Ending Choice
finalec1 = The Third Way - Part 1
finalec2 = The Third Way - Part 2
finaleb1 = The Time's Come
finalea1 = Something Sensible

// FREAKS
tonya1 = Pulling Favours
tonya2 = Pulling Another Favour
tonya3 = Pulling Favours Again
tonya4 = Still Pulling Favours
tonya5 = Pulling One Last Favour
hao1 = Shift Work
paparazzo1 = Paparazzo
paparazzo3a = Paparazzo - The Meltdown
paparazzo4 = Paparazzo - Reality Check
omega1 = Far Out
barry3a = Grass Roots - The Pickup
barry4 = Grass Roots - The Smoke - in
assassin_hooker = The Vice Assassination
assassin_bus = The Bus Assassination
assassin_multi = The Multi - Target Assassination
assassin_construction = The Construction Assassination
fanatic3 = Exercising Demons - Franklin
dreyfuss1 = A Starlet in Vinewood


// HOBBIES
golf = Golf
tennis = Tennis
triathlonsp = Triathlon(all of them I think ? )
*/